#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════════
// generate-feature.js — Scaffold new mobs, abilities, encounters, items
//
// Usage:
//   node generate-feature.js mob "Goblin" 2 0x00FF00 "A small goblin"
//   node generate-feature.js ability "Fireball" 70 2 "A ranged fire attack"
//   node generate-feature.js encounter "spider_nest" 1 3 "large" "Spawn 2-3 spiders"
//   node generate-feature.js pickup "HealthPotion" "healing" "+2 HP"
//
// Outputs a .js mod file with boilerplate ready to customize.
// ═══════════════════════════════════════════════════════════════════════════════

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
}

function kebabToCamel(str) {
    return str.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
}

function generateMob(name, hp, color, info) {
    const camelName = capitalize(kebabToCamel(name));
    const className = `com_watabou_sevendrl_characters_${camelName}`;

    return `// ═══════════════════════════════════════════════════════════════════════════════
// MOD: ${name}-mob.js — ${camelName} enemy
// Load after: rogue-api.js
//
// This is a TEMPLATE — uncomment in manifest.js to activate.
// Generated by: node generate-feature.js mob "${name}" ${hp} 0x${color.toString(16).padStart(6, '0')} "${info}"
// ═══════════════════════════════════════════════════════════════════════════════

(function() {
    'use strict';

    Rogue.Mob.define({
        name: '${name}',
        hp: ${hp},
        visual: '${name.charAt(0).toLowerCase()}',  // SWAP: change to a unique glyph
        color: 0x${color.toString(16).padStart(6, '0')},
        info: '${info}',
        damage: 1,  // SWAP: adjust damage based on difficulty
        state: 'chasing'  // 'wandering' | 'chasing'
        // Optional: onChase, onEngage, onSight, onDamage, onDeath
    });

    if (window.devLog) window.devLog('[mod:${name}-mob] loaded — ${camelName} mob registered');
})();
`;
}

function generateAbility(name, keyCode, cost, description) {
    return `// ═══════════════════════════════════════════════════════════════════════════════
// MOD: ${name}-ability.js — ${capitalize(name)} ability
// Load after: rogue-api.js
//
// This is a TEMPLATE — uncomment in manifest.js to activate.
// Generated by: node generate-feature.js ability "${name}" ${keyCode} ${cost} "${description}"
// ═══════════════════════════════════════════════════════════════════════════════

(function() {
    'use strict';

    Rogue.Ability.registerAbility(${keyCode}, {  // keyCode ${keyCode} = '${String.fromCharCode(keyCode)}'
        label: '${capitalize(name)}',
        cost: ${cost},  // stock spent per use
        description: '${description}',
        onActivate: function(game) {
            if (!game || !game.hero) return;

            // ╔══ SWAP POINT: Your ability logic here ──────────────────
            // Examples:
            // - Area damage: Rogue.Ability.dealAreaDamage(game, centerPos, radius, damage)
            // - Heal: game.hero.hp = Math.min(game.hero.hp + value, game.hero.maxHP); hero.hpChanged.dispatch(...)
            // - Buff: game.hero.damageBonus = (game.hero.damageBonus || 0) + 2;
            // - Spawn: Rogue.Encounter.spawnInRoom(game, room, MobClass, count);

            if (window.__eventLogAdd) window.__eventLogAdd('${capitalize(name)} activated!');
        }
    });

    if (window.devLog) window.devLog('[mod:${name}-ability] loaded — ${capitalize(name)} ability registered (key ${keyCode})');
})();
`;
}

function generateEncounter(name, minLevel, maxLevel, roomSize, description) {
    return `// ═══════════════════════════════════════════════════════════════════════════════
// MOD: ${name}-encounter.js — ${capitalize(name)} room encounter
// Load after: rogue-api.js
//
// This is a TEMPLATE — uncomment in manifest.js to activate.
// Generated by: node generate-feature.js encounter "${name}" ${minLevel} ${maxLevel} "${roomSize}" "${description}"
// ═══════════════════════════════════════════════════════════════════════════════

(function() {
    'use strict';

    Rogue.onReady(function() {
        Rogue.Encounter.define({
            name: '${name}',
            minLevel: ${minLevel},
            maxLevel: ${maxLevel},
            roomSize: '${roomSize}',  // 'small' | 'large' | 'dead_end' | null (any)
            priority: 0,  // higher = checked first
            once: true,  // only trigger once per game
            onEnter: function(game, room) {
                // ╔══ SWAP POINT: Spawn mobs or trigger logic ──────────
                // Resolve the mob class (or create an inline one with Rogue.Mob.define)
                // var MobClass = window['com.watabou.sevendrl.characters.YourMob'.replace(/\./g, '_')];
                // return Rogue.Encounter.spawnInRoom(game, room, MobClass, count);

                if (window.__eventLogAdd) window.__eventLogAdd('${capitalize(name)} triggered: ${description}');
                return [];  // no mobs, just a lore trigger — remove this if spawning
            }
        });

        if (window.devLog) window.devLog('[mod:${name}-encounter] loaded — ${capitalize(name)} encounter registered');
    });
})();
`;
}

function generatePickup(name, type, effect) {
    const camelName = capitalize(kebabToCamel(name));

    return `// ═══════════════════════════════════════════════════════════════════════════════
// MOD: ${name}-pickup.js — ${camelName} collectible
// Load after: rogue-api.js
//
// This is a TEMPLATE — uncomment in manifest.js to activate.
// Generated by: node generate-feature.js pickup "${name}" "${type}" "${effect}"
// ═══════════════════════════════════════════════════════════════════════════════

(function() {
    'use strict';

    var Clue = ModLoader.resolve('com.watabou.sevendrl.characters.Clue');
    var CharacterSprite = ModLoader.resolve('com.watabou.sevendrl.visuals.CharacterSprite');
    if (!Clue || !CharacterSprite) {
        if (window.devLog) window.devLog('[${name}-pickup] SKIPPED: Clue/CharacterSprite not available');
        return;
    }

    var ${camelName} = function(game, pos) {
        Clue.call(this, game, pos);
    };
    ${camelName}.__name__ = 'com.watabou.sevendrl.characters.${camelName}';
    ${camelName}.__super__ = Clue;
    ${camelName}.prototype = Object.create(Clue.prototype);
    ${camelName}.prototype.__class__ = ${camelName};

    ${camelName}.prototype.createSprite = function() {
        this.sprite = new CharacterSprite(this, '!');  // SWAP: glyph
        this.sprite.tf.set_textColor(0xFFAA00);  // SWAP: color
        this.sprite.setScale(0.8);
    };
    ${camelName}.prototype.blocks = function() { return false; };
    ${camelName}.prototype.getInfo = function() { return '${effect}'; };

    ${camelName}.prototype.collect = function() {
        var hero = this.game.hero;

        // ╔══ SWAP POINT: Your pickup effect ─────────────────
        // Examples:
        // - Heal: hero.hp = Math.min(hero.hp + 2, hero.maxHP); hero.hpChanged.dispatch(hero.hp);
        // - Stock: window.__abilityStock = (window.__abilityStock || 0) + 1;
        // - Buff: hero.maxHP = (hero.maxHP || 6) + 1;
        // - Event: if (window.__eventLogAdd) window.__eventLogAdd('...');

        if (window.__eventLogAdd) window.__eventLogAdd('Collected: ${camelName}. ${effect}');
        this.sprite.despawn();
        this.game.queue.splice(this.game.queue.indexOf(this), 1);
    };

    window.${className} = ${camelName};

    ModLoader.after('com.watabou.sevendrl.SevenDRL', 'spawnClues', function() {
        var AE = window.com_watabou_utils_ArrayExtender;
        var cells = AE.difference(this.cells, this.hero.getFOV())
            .filter(function(c) { return c !== this.hero.pos && !this.getChar(c); }, this);
        if (!cells.length) return;
        var pos = AE.random(cells);
        var item = new ${camelName}(this, pos);
        item.setPos(pos);
        this.queue.push(item);
        if (window.devLog) window.devLog('[${name}-pickup] spawned 1');
    });

    if (window.devLog) window.devLog('[mod:${name}-pickup] loaded — ${camelName} pickup registered');
})();
`;
}

function main() {
    const args = process.argv.slice(2);

    if (args.length < 2) {
        console.log(`Usage:
  node generate-feature.js mob <name> <hp> <color> <info>
  node generate-feature.js ability <name> <keyCode> <cost> <description>
  node generate-feature.js encounter <name> <minLevel> <maxLevel> <roomSize> <description>
  node generate-feature.js pickup <name> <type> <effect>

Examples:
  node generate-feature.js mob "Goblin" 2 0xFF00FF "A small goblin"
  node generate-feature.js ability "Fireball" 70 2 "A ranged fire attack"
  node generate-feature.js encounter "spider_nest" 1 3 "large" "Arachnid lair"
  node generate-feature.js pickup "HealthPotion" "healing" "+2 HP"
        `);
        process.exit(1);
    }

    const type = args[0];
    let content = '';
    let filename = '';

    if (type === 'mob' && args.length >= 5) {
        const name = args[1];
        const hp = parseInt(args[2]);
        const color = parseInt(args[3]);
        const info = args.slice(4).join(' ');
        content = generateMob(name, hp, color, info);
        filename = `${name}-mob.js`;
    } else if (type === 'ability' && args.length >= 5) {
        const name = args[1];
        const keyCode = parseInt(args[2]);
        const cost = parseInt(args[3]);
        const description = args.slice(4).join(' ');
        content = generateAbility(name, keyCode, cost, description);
        filename = `${name}-ability.js`;
    } else if (type === 'encounter' && args.length >= 6) {
        const name = args[1];
        const minLevel = parseInt(args[2]);
        const maxLevel = parseInt(args[3]);
        const roomSize = args[4];
        const description = args.slice(5).join(' ');
        content = generateEncounter(name, minLevel, maxLevel, roomSize, description);
        filename = `${name}-encounter.js`;
    } else if (type === 'pickup' && args.length >= 4) {
        const name = args[1];
        const subtype = args[2];
        const effect = args.slice(3).join(' ');
        content = generatePickup(name, subtype, effect);
        filename = `${name}-pickup.js`;
    } else {
        console.error('Invalid arguments for feature type:', type);
        process.exit(1);
    }

    const modsDir = path.join(__dirname, '../mods');
    const filepath = path.join(modsDir, filename);

    if (fs.existsSync(filepath)) {
        console.error(`Error: ${filename} already exists`);
        process.exit(1);
    }

    fs.writeFileSync(filepath, content);
    console.log(`✓ Generated: ${filename}`);
    console.log(`  Next: uncomment in Dev-Tools/mods/manifest.js`);
    console.log(`  Then: reload the game and test with DBG commands`);
}

main();
