// ═══════════════════════════════════════════════════════════════════
// INDEX — Module entry point for Dark Clues
// Generated by extract-seven-drl.js
//
// Load order follows the dependency graph in DEPENDENCIES.md.
// Runtime base MUST load first (provides Lime/OpenFL/Haxe globals).
//
// Paths here are relative to THIS file's own location (modules/) —
// no import map needed. See modules/DECISIONS.md for why the original
// paths (written as if this file lived at the project root) never
// worked: import map "./"-prefixed keys are resolved relative to the
// document, not the importing module, so they could never match these
// specifiers regardless of where the map redirected them.
// ═══════════════════════════════════════════════════════════════════

// Layer 0: Runtime (Lime/OpenFL/Haxe stdlib — no game code)
import "../runtime/base.js";

// Layer 1: Watabou shared libraries (no game dependencies)
import "./watabou/geom.js";       // Color, GeomUtils, Rect
import "./watabou/utils.js";      // ArrayExtender, Random, MathUtils, etc.
import "./watabou/processes.js";  // Process, Sequence, Tweener
import "./watabou/engine.js";     // Game, Scene, Text

// Layer 2: Tracery (procedural text generation)
import "./tracery/tracery.js";    // Grammar, Symbol, TraceryNode

// Layer 3: Core game infrastructure (depends on watabou)
import "./core/style.js";         // Style
import "./core/audio.js";         // Sounds
import "./core/visuals.js";       // AsciiSprite, CharacterSprite, etc.
import "./core/states.js";        // State, StateIdle, StateWandering, StateChasing

// Layer 4: Game logic (depends on everything above)
import "./core/pathfinding.js";   // Pathfinder
import "./core/game.js";          // Grid, Plan, Room, Door, SevenDRL, etc.
import "./core/characters.js";    // Character, Hero, Mob, Hunter, etc.
import "./core/actions.js";       // Action, ActionMove, ActionAttack, etc.

// Layer 5: Scenes (top-level, depends on game logic)
import "./core/scenes.js";        // TextScene, GameScene, DeathScene, etc.
